"project_id": "380544"
"api_token": "_secret_"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files":
  [
    {
      "source": "/intl/_core_name_/_us.json",
      "dest": "/_core_name_/_core_name_.json",
      "translation": "/intl/_core_name_/_%two_letters_code%.json",
    },
  ]
