/* Copyright (c) 2013-2014 Jeffrey Pfau
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
#ifndef EMITTER_THUMB_H
#define EMITTER_THUMB_H

#include "emitter-inlines.h"

#define DECLARE_INSTRUCTION_THUMB(EMITTER, NAME) \
	EMITTER ## NAME

#define DECLARE_THUMB_EMITTER_BLOCK(EMITTER) \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, LSL1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, LSR1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, ASR1)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, ADD3)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, SUB3)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, ADD1)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, SUB1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, MOV1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, CMP1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, ADD2)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, SUB2)), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, AND_EOR_LSL2_LSR2), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ASR2_ADC_SBC_ROR), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, TST_NEG_CMP2_CMN), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ORR_MUL_BIC_MVN), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ADD4), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, CMP3), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, MOV3), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BX_ILL), \
	DO_2(DO_4(DECLARE_INSTRUCTION_THUMB(EMITTER, LDR3))), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, STR2)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, STRH2)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, STRB2)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, LDRSB)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, LDR2)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, LDRH2)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, LDRB2)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, LDRSH)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, STR1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, LDR1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, STRB1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, LDRB1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, STRH1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, LDRH1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, STR3)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, LDR4)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, ADD5)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, ADD6)), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ADD7_SUB4), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ILL), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ILL), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ILL), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, PUSH), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, PUSHR), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, ILL)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, ILL)), \
	DO_2(DECLARE_INSTRUCTION_THUMB(EMITTER, ILL)), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, POP), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, POPR), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BKPT), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ILL), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, STMIA)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, LDMIA)), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BEQ), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BNE), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BCS), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BCC), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BMI), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BPL), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BVS), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BVC), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BHI), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BLS), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BGE), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BLT), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BGT), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, BLE), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, ILL), \
	DECLARE_INSTRUCTION_THUMB(EMITTER, SWI), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, B)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, ILL)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, BL1)), \
	DO_8(DECLARE_INSTRUCTION_THUMB(EMITTER, BL2)) \

#endif
