local state = {}
state.width = canvas:screenWidth()
state.height = canvas:screenHeight()
state.overlay = canvas:newLayer(state.width, state.height)
state.painter = image.newPainter(state.overlay.image)
state.painter:loadFont(script.dir .. "/SourceSans3-Regular.otf")
state.painter:setFontSize(9)
state.painter:setFill(true)
state.painter:setBlend(true)

state.painter:setFillColor(0xFFFFFFFF)
state.painter:drawText("Top left", 0, 0, C.ALIGN.TOP | C.ALIGN.LEFT)
state.painter:setFillColor(0xFF00FFFF)
state.painter:drawText("Top center", state.width / 2, 0, C.ALIGN.TOP | C.ALIGN.HCENTER)
state.painter:setFillColor(0xFFFF00FF)
state.painter:drawText("Top right", state.width, 0, C.ALIGN.TOP | C.ALIGN.RIGHT)

state.painter:setFillColor(0xFFFFFF00)
state.painter:drawText("Center left", 0, state.height / 2, C.ALIGN.VCENTER | C.ALIGN.LEFT)
state.painter:setFillColor(0xFFFF0000)
state.painter:drawText("Center", state.width / 2, state.height / 2, C.ALIGN.VCENTER | C.ALIGN.HCENTER)
state.painter:setFillColor(0xFF00FF00)
state.painter:drawText("Center right", state.width, state.height / 2, C.ALIGN.VCENTER | C.ALIGN.RIGHT)

state.painter:setFillColor(0xFF0000FF)
state.painter:drawText("Bottom left", 0, state.height, C.ALIGN.BOTTOM | C.ALIGN.LEFT)
state.painter:setFillColor(0xFF000000)
state.painter:drawText("Bottom center", state.width / 2, state.height, C.ALIGN.BOTTOM | C.ALIGN.HCENTER)
state.painter:setFillColor(0xFF808080)
state.painter:drawText("Bottom right", state.width, state.height, C.ALIGN.BOTTOM | C.ALIGN.RIGHT)
state.overlay:update()
